name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull latest Docker image
        run: |
          sudo docker pull ${{ secrets.IMAGE_NAME }}:latest

      - name: Run reload.sh
        run: |
          chmod +x /home/ubuntu/scripts/reload.sh
          /home/ubuntu/scripts/reload.sh
