name: CI

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{secrets.IMAGE_NAME}}
      TAG: latest

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Set up Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$TAG .

      # 4️⃣ Push the image to Docker Hub
      - name: Push Docker image
        run: docker push $IMAGE_NAME:$TAG
